FROM composer:2.1.8 AS drupal-builder

ENV DRUPAL_ROOT $DRUPAL_ROOT

COPY drupal/composer.json .
COPY drupal/composer.lock .

RUN composer global require drush/drush:~10 \
	&& composer install --ignore-platform-reqs \
	&& composer clearcache

FROM alpine:3.12.3 AS drupal

# add all packages
RUN apk update && apk upgrade && apk add \
	apache2-proxy \
	apache2-ssl \
	php7-fpm \
	php7 \
	php7-opcache \
	php7-gd \
	php7-json \
	php7-phar \
	php7-iconv \
	php7-mbstring \
	php7-zlib \
	php7-curl \
	php7-session \
	php7-redis \
	php7-pdo_mysql \
	php7-tokenizer \
	php7-dom \
	php7-simplexml \
	php7-xml \
	php7-ctype \
	mysql-client \
	'memcached=~1.6' \
	'php7-pecl-memcache=~4.0' \
	curl \ 
	&& cp /usr/bin/php7 /usr/bin/php \
    && rm -f /var/cache/apk/* \
	&& rm -rf /etc/init.d/* \
    && addgroup -g 1000 -S http \
    && adduser -G http -u 1000 -s /bin/sh -D http \
	&& sed -rie 's|;error_log = log/php7/error.log|error_log = /dev/stdout|g' /etc/php7/php-fpm.conf 

# setup apache
COPY phase1/docker/apache.conf /etc/apache2/httpd.conf
COPY phase1/docker/php-pool.conf /etc/php7/php-fpm.d/www.conf
COPY phase1/docker/php.ini /etc/php7/php.ini

# setup entrypoint file
ADD phase1/docker/scripts /bootstrap/

# expose on port 80 and set workdir
EXPOSE 80
WORKDIR ${DRUPAL_ROOT}

# Copy Drupal and dependencies from composer install above
COPY --chown=http:http --from=drupal-builder /app/web ${DRUPAL_ROOT}/web
COPY --chown=http:http --from=drupal-builder /app/vendor ${DRUPAL_ROOT}/vendor
COPY --chown=http:http drupal .

# Create symlink for drush
RUN ln -s ${DRUPAL_ROOT}/vendor/drush/drush/drush /usr/local/bin/drush

# send it
CMD ["/bootstrap/entrypoint.sh"]