version: '3'

services:
    web:
        container_name: '${PROJECT_NAME}_web'
        build:
          context: ../
          dockerfile: ./phase1/docker/dockerfile
          args:
            - DRUPAL_ROOT=${DRUPAL_ROOT}
        volumes:
            - ../drupal/storage:${DRUPAL_ROOT}/web/sites/default/files
            - ../drupal/config:${DRUPAL_ROOT}/config
            - ../drupal/modules/custom:${DRUPAL_ROOT}/web/modules/custom
        links:
            - db:db
        ports:
            - '80:80'
        env_file:
            - .env
        networks:
            - govcon-local

volumes:
    sql:

networks:
    govcon-local:
        driver: bridge