version: '3'

services:
    web:
        container_name: '${PROJECT_NAME}_web'
        build:
          context: ../
          dockerfile: ./phase2/docker/dockerfile
          args:
            - DRUPAL_ROOT=${DRUPAL_ROOT}
        volumes:
            - ../drupal/public-files:${DRUPAL_ROOT}/web/sites/default/files
            - ../drupal/private-files:${DRUPAL_ROOT}/private-files
            - ../drupal/config:${DRUPAL_ROOT}/config
            - ../drupal/custom-modules:${DRUPAL_ROOT}/web/modules/custom
        ports:
            - '80:80'
        env_file:
            - .env
        networks:
            - govcon-local

    memcache:
        container_name: '${PROJECT_NAME}_memcache'
        image: memcached:1.6.10-buster
        ports:
          - '11211:11211'
        networks:
            - govcon-local

networks:
    govcon-local:
        driver: bridge