AWSTemplateFormatVersion: 2010-09-09

Parameters:
  OriginDomainName:
    Description: DNS Value for the Origin
    Type: String

  DomainCNAME:
    Description: Domain to use as an Alias for the Cloudfront Distribution
    Type: String

  CertificateARN:
    Description: AWS ACM Certificate ARN used for the distribution
    Type: String

Resources:
  CFDistribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        Aliases: 
        - !Ref DomainCNAME
        DefaultCacheBehavior: 
          AllowedMethods: 
          - GET
          - HEAD
          CachedMethods: 
          - GET
          - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: nginx
          ViewerProtocolPolicy: redirect-to-https
        Comment: String
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins: 
        - DomainName: !Ref OriginDomainName
          Id: nginx
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: match-viewer
            OriginSSLProtocols:
              - TLSv1.2
              - SSLv3
        PriceClass: PriceClass_All
        ViewerCertificate: 
          AcmCertificateArn: !Ref CertificateARN
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

Outputs:
  CloudFrontDomainName:
    Description: "ALB DNS Name"
    Value: !GetAtt [CFDistribution, DomainName]

