version: '3'

services:
    rproxy:
        container_name: '${PROJECT_NAME}_rproxy'
        image: nginx:1.19.6-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/templates/default.conf.template
        ports:
            - '80:80'
        env_file:
            - .env
        networks:
            - govcon-local

networks:
    govcon-local:
        driver: bridge