version: '3'

services:
    web:
        container_name: '${PROJECT_NAME}_web'
        build:
          context: ../
          dockerfile: ./step1/docker/dockerfile
        volumes:
            - ./step1/docker/drupal/storage:/var/www/drupal/web/sites/default/files
            - ./step1/docker/drupal/config:/var/www/drupal/config
        links:
            - db:db
        ports:
            - '80:80'
        env_file:
            - .env
        networks:
            - govcon-local

    db:
        container_name: '${PROJECT_NAME}_db'
        image: mariadb:10.6
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - sql:/var/lib/mysql
            - ./docker/db/manual_sql_dumps:/var/lib/mysql/dumps
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        networks:
            - govcon-local
        env_file:
            - .env

    memcache:
        container_name: '${PROJECT_NAME}_memcache'
        image: memcached:1.6.10-buster
        ports:
          - '11211:11211'
        networks:
            - govcon-local

volumes:
    sql:

networks:
    govcon-local:
        driver: bridge