version: '3'

services:
    web:
        container_name: '${PROJECT_NAME}_web'
        build:
          context: ../
          dockerfile: ./step2-rds/docker/dockerfile
        volumes:
            - ../drupal/storage:/var/www/drupal/web/sites/default/files
            - ../drupal/config:/var/www/drupal/config
        links:
            - db:db
        ports:
            - '80:80'
        env_file:
            - .env
        networks:
            - govcon-local

    memcache:
        container_name: '${PROJECT_NAME}_memcache'
        image: memcached:1.6.10-buster
        ports:
          - '11211:11211'
        networks:
            - govcon-local

networks:
    govcon-local:
        driver: bridge