AWSTemplateFormatVersion: 2010-09-09
Description: "Elasticache Memcached Cluster"

Parameters:
  DefaultSecurityGroupId:
    Description: ID of default security group from default VPC
    Type: String

Resources:
  ElasticacheSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Elasticache Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 11211
          ToPort: 11211
          SourceSecurityGroupId: !Ref DefaultSecurityGroupId

  ElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties: 
      Description: SubnetGroups for Elasticache Cluster
      SubnetIds: 
        - subnet-3a41280b
        - subnet-79496c1f
        - subnet-d1c2e2f0

  ElasticacheCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:    
      Engine: memcached
      EngineVersion: 1.6.6
      CacheNodeType: cache.t2.micro
      CacheSubnetGroupName: !Ref ElasticacheSubnetGroup
      CacheParameterGroupName: default.memcached1.6
      NumCacheNodes: '1'
      VpcSecurityGroupIds:
        - !GetAtt  ElasticacheSecurityGroup.GroupId
      Port: 11211
      PreferredMaintenanceWindow: sun:23:00-mon:01:30

  DNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : Z01629752800X7928YLRP
      Name: cache.govcon2021.mobomo.net
      ResourceRecords:
      - !GetAtt [ElasticacheCluster, ConfigurationEndpoint.Address]
      TTL: 60
      Type: CNAME

